sonar.projectKey=conchayoro
sonar.projectName=conchayoro
sonar.organization=valuedriven
sonar.language=js
sonar.lang.patterns.js=**/*.js,**/*.jsx,**/*.vue
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.scm.disabled=true
sonar.scm.provider.disabled=true
sonar.scm.enabled=true
sonar.verbose=true
sonar.projectBaseDir=.
sonar.sources=backend/src
sonar.tests=backend/src/test
sonar.exclusions=**/node_modules/**, **/coverage/**, package*.json, **/builds/**, **/src/db/**, **/src/test/**
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=tmp/coverage/lcov.info
sonar.eslint.reportPaths=tmp/eslint-report.json