version: '3.7'

services:
  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: 'conchayorodb'
      MYSQL_USER: 'conchayorouser'
      MYSQL_PASSWORD: 'conchayoropwd'
      MYSQL_ROOT_PASSWORD: 'conchayoropwd'
    ports:
      - '3306:3306'