---
- name: Deploy static content to AWS S3
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_files:
    - vars/global.yml

  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"

  # vars:
  #   bucket_name: "{{ lookup('env', 'BUCKET_NAME') }}"
  #   file_to_upload: "{{ lookup('env', 'FILE_TO_UPLOAD') }}"

  tasks:
    - name: Bucket creation
      amazon.aws.s3_bucket:
        name: '{{ bucket_name }}'
        state: present
        acl: public-read
    - name: Upload/PUT file to S3 bucket
      amazon.aws.aws_s3:
        bucket: '{{ bucket_name }}'
        mode: put
        object: '{{ file_to_upload }}'
        src: '{{ file_to_upload }}'
      register: putresult
    - debug: 
        msg="{{ putresult.msg }} and the S3 Object URL is {{putresult.url}}" 
      when: putresult.changed
