name: ManageRegistry

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: sa-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:  
  setup-registry:
    runs-on: ubuntu-latest
    steps:    
    # - run: ansible-playbook ambiente/manage-registry.yml
    - uses: actions/checkout@v2    
    - run: ls -la

  