name: Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: sa-east-1
  ANSIBLE_REMOTE_USER: ec2-user
  ANSIBLE_PRIVATE_KEY_FILE: ambiente/conchayoro-key
  ANSIBLE_HOST_KEY_CHECKING: False
  IMAGE_TAG: latest
  PROJECT_NAME: conchayoro
  DATABASE_PROJECT: db
  DATABASE_IMAGE: conchayoro/db:latest
  BACKEND_PROJECT: backend
  BACKEND_IMAGE: conchayoro/backend:latest
  FRONTEND_PROJECT: frontend
  FRONTEND_IMAGE: conchayoro/frontend:latest
  ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  
jobs:
  # verify:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2    
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
  #       cache: 'npm'
  #   - run: npm install eslint eslint-config-prettier eslint-plugin-prettier prettier-eslint --save-dev
  #   - run: npm install eslint-plugin-vue --save-dev --prefix=frontend
  #   - run: npm run eslint

  # build-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2    
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
  #       cache: 'npm'
  #   - run: npm ci --prefix=backend
  #   - name: Configuração de credenciais AWS
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: sa-east-1
  #   - name: Login to Amazon ECR
  #     id: login-ecr
  #     uses: aws-actions/amazon-ecr-login@v1
  #   - name: Build, tag, e push de imagem para Amazon ECR
  #     env:
  #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #     run: |
  #       docker build -t $ECR_REGISTRY/$BACKEND_PROJECT:$IMAGE_TAG $BACKEND_PROJECT
  #       docker push $ECR_REGISTRY/$BACKEND_PROJECT:$IMAGE_TAG

  # build-frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2    
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
  #       cache: 'npm'
  #   - run: npm ci --prefix=frontend
  #   - run: npm run build --prefix=frontend
  #   - name: Configuração de credenciais AWS
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: sa-east-1
  #   - name: Login to Amazon ECR
  #     id: login-ecr
  #     uses: aws-actions/amazon-ecr-login@v1
  #   - name: Build, tag, e push de imagem para Amazon ECR
  #     env:
  #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #     run: |
  #       docker build -t $ECR_REGISTRY/$FRONTEND_PROJECT:$IMAGE_TAG $FRONTEND_PROJECT
  #       docker push $ECR_REGISTRY/$FRONTEND_PROJECT:$IMAGE_TAG
              
  build-db:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Configuração de credenciais AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, e push de imagem para Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo "ECR_REGISTRY: $ECR_REGISTRY"
        docker build -t $ECR_REGISTRY/$DATABASE_PROJECT:$IMAGE_TAG $DATABASE_PROJECT
        docker push $ECR_REGISTRY/$DATABASE_PROJECT:$IMAGE_TAG

  setup-registry:
    runs-on: ubuntu-latest        
    steps:    
    - uses: actions/checkout@v2
    - run: ls -la 
    - run: ansible-playbook ambiente/manage-registry.yml -e 'ansible_python_interpreter=/usr/bin/python3'

  # deployment-cloud:
  #   needs: push-images
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: ansible-galaxy collection install -r ambiente/requirements.yml
  #   - run: ansible-playbook ambiente/keys.yml
  #   - run: ansible-playbook ambiente/provisioning.yml
  #   - run: ansible-playbook ambiente/install-packages.yml --inventory ambiente/inventory.aws_ec2.yml
  #   - run: ansible-playbook ambiente/deploy-images.yml --inventory ambiente/inventory.aws_ec2.yml 
  
  # deployment-cloud:
  #   env:
  #     ANSIBLE_REMOTE_USER: ec2-user
  #     ANSIBLE_PRIVATE_KEY_FILE: ambiente/conchayoro-key
  #     ANSIBLE_HOST_KEY_CHECKING: False
  #   steps:
  #     - uses: ./.github/actions/ansible
  #       with: 
  #         playbook: ambiente/keys.yml
  #         inventory: localhost

  #     - uses: ./.github/actions/ansible
  #       with: 
  #         playbook: ambiente/provisioning.yml
  #         inventory: localhost

  #     - uses: ./.github/actions/ansible
  #       with: 
  #         playbook: ambiente/install-packages.yml
  #         inventory: ambiente/inventory.aws_ec2.yml

  #     - uses: ./.github/actions/ansible
  #       with: 
  #         playbook: ambiente/deploy-images.yml
  #         inventory: ambiente/inventory.aws_ec2.yml          

