name: Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ANSIBLE_REMOTE_USER: ec2-user
  ANSIBLE_PRIVATE_KEY_FILE: ambiente/conchayoro-key
  ANSIBLE_HOST_KEY_CHECKING: 'False'
  TAG: latest
  PROJECT_NAME: conchayoro
  DATABASE_PROJECT: db
  DATABASE_IMAGE: conchayoro/db:latest
  BACKEND_PROJECT: backend
  BACKEND_IMAGE: conchayoro/backend:latest
  FRONTEND_PROJECT: frontend
  FRONTEND_IMAGE: conchayoro/frontend:latest
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
          path: |
            ~/.npm
            db
            frontend/node_modules
            backend/node_modules
          # key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          # restore-keys: |
          #   ${{ runner.os }}-build-${{ env.cache-name }}-
          #   ${{ runner.os }}-build-
          #   ${{ runner.os }}-
    - run: npm install eslint eslint-config-prettier eslint-plugin-prettier prettier-eslint --save-dev
    - run: npm install eslint-plugin-vue --save-dev --prefix=frontend
    - run: npm run eslint
    - run: npm ci --prefix=backend
    - run: npm ci --prefix=frontend
    - run: npm run build --prefix=frontend
    #- run: npm run test:unit -- --passWithNoTests
    - uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          frontend/dist
    
  build-image-db:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: docker build -t $DATABASE_IMAGE $DATABASE_PROJECT
  
  build-image-frontend:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: docker build -t $FRONTEND_IMAGE $FRONTEND_PROJECT

  build-image-backend:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: docker build -t $BACKEND_IMAGE $BACKEND_PROJECT

  push-images:
    needs: [ build-image-db, build-image-frontend, build-image-backend ]
    runs-on: ubuntu-latest
    steps:
    - run: go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
    - run: ansible-playbook ambiente/push-images.yml

  # deployment-cloud:    
  #   needs: push-images
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: ansible-galaxy collection install -r ambiente/requirements.yml
  #   - run: ansible-playbook ambiente/keys.yml
  #   - run: ansible-playbook ambiente/provisioning.yml
  #   - run: ansible-playbook ambiente/install-packages.yml --inventory ambiente/inventory.aws_ec2.yml
  #   - run: ansible-playbook ambiente/deploy-images.yml --inventory ambiente/inventory.aws_ec2.yml 

  # push-images:
  #   uses: actions/setup-go@v2.1.4
  #   steps:
  #   - run: go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
  #   - uses: ./.github/actions/ansible
  #     with: 
  #       playbook: ambiente/push-images.yml
  #       inventory: localhost
    
  # deployment-cloud:
  #   env:
  #     ANSIBLE_REMOTE_USER: ec2-user
  #     ANSIBLE_PRIVATE_KEY_FILE: ambiente/conchayoro-key
  #     ANSIBLE_HOST_KEY_CHECKING: False
  #   steps:
  #     - uses: ./.github/actions/ansible
  #       with: 
  #         playbook: ambiente/keys.yml
  #         inventory: localhost

  #     - uses: ./.github/actions/ansible
  #       with: 
  #         playbook: ambiente/provisioning.yml
  #         inventory: localhost

  #     - uses: ./.github/actions/ansible
  #       with: 
  #         playbook: ambiente/install-packages.yml
  #         inventory: ambiente/inventory.aws_ec2.yml

  #     - uses: ./.github/actions/ansible
  #       with: 
  #         playbook: ambiente/deploy-images.yml
  #         inventory: ambiente/inventory.aws_ec2.yml          

