name: deploy-s3-terraform

on:
  push
  #workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run:  echo "<h1>Hello Conchayoro</h1>" > /var/www/html/index.html
    - uses: actions/upload-artifact@v4
      with:
        name: site
        path: index.html

  provisioning:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - run:  terraform -chdir=.infra init -input=false 
    - run:  terraform -chdir=.infra plan -input=false
    - run:  terraform -chdir=.infra deploy -input=false

  deploy:
    runs-on: ubuntu-latest
    needs: provisioning
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      #AWS_EC2_METADATA_DISABLED: true
      BUCKET_S3: ${{ vars.BUCKET_S3 }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: site
        path: index.html
    - run: aws s3 cp index.html s3://$BUCKET_S3 --recursive --acl public-read
